---
- name: Ensure application is deployed
  hosts: localhost

  become: true
  vars_files:
    - "files/secrets/devops.yml"

  tasks:
    - block:
      - name: Check that you can connect to webpage
        uri:
          url: http://{{ ip_addr_preprod }}:{{ port_app }}
        retries: 8
        delay: 20

      - name: Check webservice application production
        uri:
          url: http://{{ ip_addr_preprod }}:{{ port_app }}/health
          method: GET
        retries: 8
        delay: 20
      tags:
       - preprod

    - block:
      - name: Check that you can connect to webpage
        uri:
          url: http://{{ ip_addr_prod }}:{{ port_app }}
        retries: 8
        delay: 20

      - name: Check webservice application production
        uri:
          url: http://{{ ip_addr_prod }}:{{ port_app }}/health
          method: GET
        retries: 8
        delay: 20
      tags:
        - prod
